In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
from sklearn.decomposition import PCA

In [5]:
print (tf.__version__)
print (np.__version__)
print (pd.__version__)

1.13.1
1.16.2
0.24.2


In [24]:
automobile_df = pd.read_csv('datasets/imports-85.data',sep=r'\s*,\s*',engine='python',header=None,
                            names=['symboling',    'normalized-losses', 'make', 'fuel-type', 'aspiration',
                                   'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
                                   'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
                                   'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
                                   'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg',
                                   'price'])
automobile_df.head()

symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3                 ?  alfa-romero       gas        std          two   
1          3                 ?  alfa-romero       gas        std          two   
2          1                 ?  alfa-romero       gas        std          two   
3          2               164         audi       gas        std         four   
4          2               164         audi       gas        std         four   

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
0  convertible          rwd           front        88.6  ...          130   
1  convertible          rwd           front        88.6  ...          130   
2    hatchback          rwd           front        94.5  ...          152   
3        sedan          fwd           front        99.8  ...          109   
4        sedan          4wd           front        99.4  ...          136   

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
0         mpfi  3.47    2.68               9.0        111      5000       21   
1         mpfi  3.47    2.68               9.0        111      5000       21   
2         mpfi  2.68    3.47               9.0        154      5000       19   
3         mpfi  3.19    3.40              10.0        102      5500       24   
4         mpfi  3.19    3.40               8.0        115      5500       18   

  highway-mpg  price  
0          27  13495  
1          27  16500  
2          26  16500  
3          30  13950  
4          22  17450  

[5 rows x 26 columns]

In [25]:
automobile_df = automobile_df.replace('?', np.nan)
automobile_df = automobile_df.dropna()

In [26]:
automobile_df = automobile_df[['engine-size','wheel-base','stroke','highway-mpg']]
automobile_df.head()

engine-size  wheel-base stroke  highway-mpg
3           109        99.8   3.40           30
4           136        99.4   3.40           22
6           136       105.8   3.40           25
8           131       105.8   3.40           20
10          108       101.2   2.80           29

In [27]:
automobile_df.describe()

engine-size  wheel-base  highway-mpg
count   159.000000  159.000000   159.000000
mean    119.226415   98.264151    32.081761
std      30.460791    5.167416     6.459189
min      61.000000   86.600000    18.000000
25%      97.000000   94.500000    28.000000
50%     110.000000   96.900000    32.000000
75%     135.000000  100.800000    37.000000
max     258.000000  115.600000    54.000000

In [28]:
auto_arr = automobile_df.values[:20]

In [29]:
auto_arr = auto_arr.astype(np.float64)

In [32]:
auto_arr

array([[109.  ,  99.8 ,   3.4 ,  30.  ],
       [136.  ,  99.4 ,   3.4 ,  22.  ],
       [136.  , 105.8 ,   3.4 ,  25.  ],
       [131.  , 105.8 ,   3.4 ,  20.  ],
       [108.  , 101.2 ,   2.8 ,  29.  ],
       [108.  , 101.2 ,   2.8 ,  29.  ],
       [164.  , 101.2 ,   3.19,  28.  ],
       [164.  , 101.2 ,   3.19,  28.  ],
       [ 61.  ,  88.4 ,   3.03,  53.  ],
       [ 90.  ,  94.5 ,   3.11,  43.  ],
       [ 90.  ,  94.5 ,   3.11,  43.  ],
       [ 90.  ,  93.7 ,   3.23,  41.  ],
       [ 90.  ,  93.7 ,   3.23,  38.  ],
       [ 98.  ,  93.7 ,   3.39,  30.  ],
       [ 90.  ,  93.7 ,   3.23,  38.  ],
       [ 90.  ,  93.7 ,   3.23,  38.  ],
       [ 90.  ,  93.7 ,   3.23,  38.  ],
       [122.  , 103.3 ,   3.46,  30.  ],
       [156.  ,  95.9 ,   3.9 ,  24.  ],
       [ 92.  ,  86.6 ,   3.41,  54.  ]])

In [33]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
auto_arr_scaled = scaler.fit_transform(auto_arr)

In [34]:
auto_arr_scaled

array([[-0.06275718,  0.52931127,  0.60902918, -0.43584306],
       [ 0.90549644,  0.45232054,  0.60902918, -1.29676764],
       [ 0.90549644,  1.68417221,  0.60902918, -0.97392092],
       [ 0.72619021,  1.68417221,  0.60902918, -1.51199878],
       [-0.09861842,  0.79877882, -1.94633801, -0.54345864],
       [-0.09861842,  0.79877882, -1.94633801, -0.54345864],
       [ 1.9096113 ,  0.79877882, -0.28534934, -0.65107421],
       [ 1.9096113 ,  0.79877882, -0.28534934, -0.65107421],
       [-1.78409695, -1.66492453, -0.96678059,  2.03931508],
       [-0.74412084, -0.4908159 , -0.62606496,  0.96315936],
       [-0.74412084, -0.4908159 , -0.62606496,  0.96315936],
       [-0.74412084, -0.64479736, -0.11499152,  0.74792822],
       [-0.74412084, -0.64479736, -0.11499152,  0.42508151],
       [-0.45723088, -0.64479736,  0.56643973, -0.43584306],
       [-0.74412084, -0.64479736, -0.11499152,  0.42508151],
       [-0.74412084, -0.64479736, -0.11499152,  0.42508151],
       [-0.74412084, -0.

In [35]:
results = PCA(n_components=4)

In [36]:
Y = results.fit_transform(auto_arr_scaled)

In [37]:
results.explained_variance_ratio_

array([0.66430416, 0.25053532, 0.05963265, 0.02552787])

In [38]:
results.components_

array([[-0.55800206, -0.53872398, -0.24219443,  0.58288252],
       [ 0.10476258, -0.39758628,  0.90503881,  0.1088793 ],
       [ 0.82316135, -0.321092  , -0.28137631,  0.37434301],
       [ 0.0079931 ,  0.66977724,  0.2075427 ,  0.71292397]])

In [39]:
np.dot(Y,results.components_)

array([[-0.06275718,  0.52931127,  0.60902918, -0.43584306],
       [ 0.90549644,  0.45232054,  0.60902918, -1.29676764],
       [ 0.90549644,  1.68417221,  0.60902918, -0.97392092],
       [ 0.72619021,  1.68417221,  0.60902918, -1.51199878],
       [-0.09861842,  0.79877882, -1.94633801, -0.54345864],
       [-0.09861842,  0.79877882, -1.94633801, -0.54345864],
       [ 1.9096113 ,  0.79877882, -0.28534934, -0.65107421],
       [ 1.9096113 ,  0.79877882, -0.28534934, -0.65107421],
       [-1.78409695, -1.66492453, -0.96678059,  2.03931508],
       [-0.74412084, -0.4908159 , -0.62606496,  0.96315936],
       [-0.74412084, -0.4908159 , -0.62606496,  0.96315936],
       [-0.74412084, -0.64479736, -0.11499152,  0.74792822],
       [-0.74412084, -0.64479736, -0.11499152,  0.42508151],
       [-0.45723088, -0.64479736,  0.56643973, -0.43584306],
       [-0.74412084, -0.64479736, -0.11499152,  0.42508151],
       [-0.74412084, -0.64479736, -0.11499152,  0.42508151],
       [-0.74412084, -0.

In [40]:
auto_arr_scaled

array([[-0.06275718,  0.52931127,  0.60902918, -0.43584306],
       [ 0.90549644,  0.45232054,  0.60902918, -1.29676764],
       [ 0.90549644,  1.68417221,  0.60902918, -0.97392092],
       [ 0.72619021,  1.68417221,  0.60902918, -1.51199878],
       [-0.09861842,  0.79877882, -1.94633801, -0.54345864],
       [-0.09861842,  0.79877882, -1.94633801, -0.54345864],
       [ 1.9096113 ,  0.79877882, -0.28534934, -0.65107421],
       [ 1.9096113 ,  0.79877882, -0.28534934, -0.65107421],
       [-1.78409695, -1.66492453, -0.96678059,  2.03931508],
       [-0.74412084, -0.4908159 , -0.62606496,  0.96315936],
       [-0.74412084, -0.4908159 , -0.62606496,  0.96315936],
       [-0.74412084, -0.64479736, -0.11499152,  0.74792822],
       [-0.74412084, -0.64479736, -0.11499152,  0.42508151],
       [-0.45723088, -0.64479736,  0.56643973, -0.43584306],
       [-0.74412084, -0.64479736, -0.11499152,  0.42508151],
       [-0.74412084, -0.64479736, -0.11499152,  0.42508151],
       [-0.74412084, -0.

In [45]:
NUM_INPUTS=4
NUM_HIDDEN=3 # Codings. Must be less than input
NUM_OUTPUTS=NUM_INPUTS

In [46]:
tf.reset_default_graph()

X      = tf.placeholder(tf.float64,shape=[None,NUM_INPUTS])
hidden = tf.layers.dense(X, NUM_HIDDEN) # No activation specified. Default = linear
outputs= tf.layers.dense(hidden, NUM_OUTPUTS) # Fully connected layer

reconstruction_loss = tf.reduce_mean(tf.square(outputs - X))

optimizer   = tf.train.AdamOptimizer(0.01) # 0.01 is the learning rate
training_op = optimizer.minimize(reconstruction_loss)

init = tf.global_variables_initializer()

In [47]:
with tf.Session() as sess:
    init.run()
    for iteration in range(10000):
        training_op.run(feed_dict={X: auto_arr_scaled})
    outputs_val = outputs.eval(feed_dict={X: auto_arr_scaled})
    print (outputs_val)

[[-0.06458525  0.41641488  0.57236628 -0.55744884]
 [ 0.90840889  0.78080732  0.70723687 -0.95023739]
 [ 0.89969915  1.30646623  0.48722572 -1.38018086]
 [ 0.72331227  1.56463765  0.56667817 -1.64402831]
 [-0.0965788   0.97125635 -1.89287096 -0.36049285]
 [-0.0965788   0.97125635 -1.89287096 -0.36049285]
 [ 1.90850831  0.78243375 -0.29374131 -0.6714303 ]
 [ 1.90850831  0.78243375 -0.29374131 -0.6714303 ]
 [-1.7831908  -1.75136693 -0.98624778  1.95373393]
 [-0.74508894 -0.64101465 -0.66945809  0.80599275]
 [-0.74508894 -0.64101465 -0.66945809  0.80599275]
 [-0.74403105 -0.69399325 -0.12760155  0.6979309 ]
 [-0.74231092 -0.5396201  -0.08019072  0.53898487]
 [-0.45220132 -0.22389095  0.6971088   0.01248327]
 [-0.74231092 -0.5396201  -0.08019072  0.53898487]
 [-0.74231092 -0.5396201  -0.08019072  0.53898487]
 [-0.74231092 -0.5396201  -0.08019072  0.53898487]
 [ 0.39717079  0.75056703  0.72118316 -0.92011506]
 [ 1.62408893  0.00709289  2.80442565 -0.84192905]
 [-0.67347317 -2.22404232  0.59

In [48]:
np.dot(Y[:,[0,1,2]], results.components_[[0,1,2]])

array([[-0.06411357,  0.41565301,  0.5738101 , -0.55682313],
       [ 0.90939632,  0.7791085 ,  0.7102904 , -0.94892816],
       [ 0.90096175,  1.30419021,  0.49128482, -1.37838118],
       [ 0.7247332 ,  1.56208245,  0.57119744, -1.6419535 ],
       [-0.09656278,  0.97103035, -1.89296274, -0.36011075],
       [-0.09656278,  0.97103035, -1.89296274, -0.36011075],
       [ 1.90939646,  0.78077587, -0.29092788, -0.6702369 ],
       [ 1.90939646,  0.78077587, -0.29092788, -0.6702369 ],
       [-1.78508681, -1.74786928, -0.99248253,  1.95102707],
       [-0.74589562, -0.63953259, -0.67214754,  0.80486242],
       [-0.74589562, -0.63953259, -0.67214754,  0.80486242],
       [-0.7446926 , -0.69270778, -0.12983744,  0.69693144],
       [-0.74285287, -0.5385484 , -0.08206834,  0.53817498],
       [-0.45220571, -0.22371656,  0.6969193 ,  0.01236355],
       [-0.74285287, -0.5385484 , -0.08206834,  0.53817498],
       [-0.74285287, -0.5385484 , -0.08206834,  0.53817498],
       [-0.74285287, -0.

In [55]:
Y[:2]

array([[-0.65168282,  0.28671926, -0.55613809,  0.16969561],
       [-1.65231146,  0.32502961, -0.05666912, -0.48790544]])

In [58]:
Y[:2,[0,1,2]]

array([[-0.65168282,  0.28671926, -0.55613809],
       [-1.65231146,  0.32502961, -0.05666912]])

In [60]:
results.components_

array([[-0.55800206, -0.53872398, -0.24219443,  0.58288252],
       [ 0.10476258, -0.39758628,  0.90503881,  0.1088793 ],
       [ 0.82316135, -0.321092  , -0.28137631,  0.37434301],
       [ 0.0079931 ,  0.66977724,  0.2075427 ,  0.71292397]])